INSERT INTO tbl_countries (name, historical, iso3166_num, iso3166_a2, iso3166_a3, category) VALUES 
('Afghanistan', 0, 4, 'AF', 'AFG', 'Sovereign State'),
('Åland Islands', 0, 248, 'AX', 'ALA', 'Autonomous Region'),
('Albania', 0, 8, 'AL', 'ALB', 'Sovereign State'),
('Algeria', 0, 12, 'DZ', 'DZA', 'Sovereign State'),
('American Samoa', 0, 16, 'AS', 'ASM', 'Dependency'),
('Andorra', 0, 20, 'AD', 'AND', 'Sovereign State'),
('Angola', 0, 24, 'AO', 'AGO', 'Sovereign State'),
('Anguilla', 0, 660, 'AI', 'AIA', 'Dependency'),
('Antarctica', 0, 10, 'AQ', 'ATA', 'Special Entity'),
('Antigua and Barbuda', 0, 28, 'AG', 'ATG', 'Sovereign State'),
('Argentina', 0, 32, 'AR', 'ARG', 'Sovereign State'),
('Armenia', 0, 51, 'AM', 'ARM', 'Sovereign State'),
('Aruba', 0, 533, 'AW', 'ABW', 'Dependency'),
('Australia', 0, 36, 'AU', 'AUS', 'Sovereign State'),
('Austria', 0, 40, 'AT', 'AUT', 'Sovereign State'),
('Azerbaijan', 0, 31, 'AZ', 'AZE', 'Sovereign State'),
('Bahamas', 0, 44, 'BS', 'BHS', 'Sovereign State'),
('Bahrain', 0, 48, 'BH', 'BHR', 'Sovereign State'),
('Bangladesh', 0, 50, 'BD', 'BGD', 'Sovereign State'),
('Barbados', 0, 52, 'BB', 'BRB', 'Sovereign State'),
('Belarus', 0, 112, 'BY', 'BLR', 'Sovereign State'),
('Belgium', 0, 56, 'BE', 'BEL', 'Sovereign State'),
('Belize', 0, 84, 'BZ', 'BLZ', 'Sovereign State'),
('Benin', 0, 204, 'BJ', 'BEN', 'Sovereign State'),
('Bermuda', 0, 60, 'BM', 'BMU', 'Dependency'),
('Bhutan', 0, 64, 'BT', 'BTN', 'Sovereign State'),
('Bolivia, Plurinational State of', 0, 68, 'BO', 'BOL', 'Sovereign State'),
('Bonaire, Sint Eustatius and Saba', 0, 535, 'BQ', 'BES', 'Special Entity'),
('Bosnia and Herzegovina', 0, 70, 'BA', 'BIH', 'Sovereign State'),
('Botswana', 0, 72, 'BW', 'BWA', 'Sovereign State'),
('Bouvet Island', 0, 74, 'BV', 'BVT', 'Special Entity'),
('Brazil', 0, 76, 'BR', 'BRA', 'Sovereign State'),
('British Indian Ocean Territory', 0, 86, 'IO', 'IOT', 'Dependency'),
('Brunei Darussalam', 0, 96, 'BN', 'BRN', 'Sovereign State'),
('Bulgaria', 0, 100, 'BG', 'BGR', 'Sovereign State'),
('Burkina Faso', 0, 854, 'BF', 'BFA', 'Sovereign State'),
('Burundi', 0, 108, 'BI', 'BDI', 'Sovereign State'),
('Cabo Verde', 0, 132, 'CV', 'CPV', 'Sovereign State'),
('Cambodia', 0, 116, 'KH', 'KHM', 'Sovereign State'),
('Cameroon', 0, 120, 'CM', 'CMR', 'Sovereign State'),
('Canada', 0, 124, 'CA', 'CAN', 'Sovereign State'),
('Cayman Islands', 0, 136, 'KY', 'CYM', 'Dependency'),
('Central African Republic', 0, 140, 'CF', 'CAF', 'Sovereign State'),
('Chad', 0, 148, 'TD', 'TCD', 'Sovereign State'),
('Chile', 0, 152, 'CL', 'CHL', 'Sovereign State'),
('China', 0, 156, 'CN', 'CHN', 'Sovereign State'),
('Christmas Island', 0, 162, 'CX', 'CXR', 'Dependency'),
('Cocos (Keeling) Islands', 0, 166, 'CC', 'CCK', 'Dependency'),
('Colombia', 0, 170, 'CO', 'COL', 'Sovereign State'),
('Comoros', 0, 174, 'KM', 'COM', 'Sovereign State'),
('Congo', 0, 178, 'CG', 'COG', 'Sovereign State'),
('Congo, Democratic Republic of the', 0, 180, 'CD', 'COD', 'Sovereign State'),
('Cook Islands', 0, 184, 'CK', 'COK', 'Autonomous Region'),
('Costa Rica', 0, 188, 'CR', 'CRI', 'Sovereign State'),
('Côte d''Ivoire', 0, 384, 'CI', 'CIV', 'Sovereign State'),
('Croatia', 0, 191, 'HR', 'HRV', 'Sovereign State'),
('Cuba', 0, 192, 'CU', 'CUB', 'Sovereign State'),
('Curaçao', 0, 531, 'CW', 'CUW', 'Dependency'),
('Cyprus', 0, 196, 'CY', 'CYP', 'Sovereign State'),
('Czechia', 0, 203, 'CZ', 'CZE', 'Sovereign State'),
('Denmark', 0, 208, 'DK', 'DNK', 'Sovereign State'),
('Djibouti', 0, 262, 'DJ', 'DJI', 'Sovereign State'),
('Dominica', 0, 212, 'DM', 'DMA', 'Sovereign State'),
('Dominican Republic', 0, 214, 'DO', 'DOM', 'Sovereign State'),
('Ecuador', 0, 218, 'EC', 'ECU', 'Sovereign State'),
('Egypt', 0, 818, 'EG', 'EGY', 'Sovereign State'),
('El Salvador', 0, 222, 'SV', 'SLV', 'Sovereign State'),
('Equatorial Guinea', 0, 226, 'GQ', 'GNQ', 'Sovereign State'),
('Eritrea', 0, 232, 'ER', 'ERI', 'Sovereign State'),
('Estonia', 0, 233, 'EE', 'EST', 'Sovereign State'),
('Eswatini', 0, 748, 'SZ', 'SWZ', 'Sovereign State'),
('Ethiopia', 0, 231, 'ET', 'ETH', 'Sovereign State'),
('Falkland Islands (Malvinas)', 0, 238, 'FK', 'FLK', 'Dependency'),
('Faroe Islands', 0, 234, 'FO', 'FRO', 'Autonomous Region'),
('Fiji', 0, 242, 'FJ', 'FJI', 'Sovereign State'),
('Finland', 0, 246, 'FI', 'FIN', 'Sovereign State'),
('France', 0, 250, 'FR', 'FRA', 'Sovereign State'),
('French Guiana', 0, 254, 'GF', 'GUF', 'Dependency'),
('French Polynesia', 0, 258, 'PF', 'PYF', 'Dependency'),
('French Southern Territories', 0, 260, 'TF', 'ATF', 'Special Entity'),
('Gabon', 0, 266, 'GA', 'GAB', 'Sovereign State'),
('Gambia', 0, 270, 'GM', 'GMB', 'Sovereign State'),
('Georgia', 0, 268, 'GE', 'GEO', 'Sovereign State'),
('Germany', 0, 276, 'DE', 'DEU', 'Sovereign State'),
('Ghana', 0, 288, 'GH', 'GHA', 'Sovereign State'),
('Gibraltar', 0, 292, 'GI', 'GIB', 'Dependency'),
('Greece', 0, 300, 'GR', 'GRC', 'Sovereign State'),
('Greenland', 0, 304, 'GL', 'GRL', 'Dependency'),
('Grenada', 0, 308, 'GD', 'GRD', 'Sovereign State'),
('Guadeloupe', 0, 312, 'GP', 'GLP', 'Dependency'),
('Guam', 0, 316, 'GU', 'GUM', 'Dependency'),
('Guatemala', 0, 320, 'GT', 'GTM', 'Sovereign State'),
('Guernsey', 0, 831, 'GG', 'GGY', 'Dependency'),
('Guinea', 0, 324, 'GN', 'GIN', 'Sovereign State'),
('Guinea-Bissau', 0, 624, 'GW', 'GNB', 'Sovereign State'),
('Guyana', 0, 328, 'GY', 'GUY', 'Sovereign State'),
('Haiti', 0, 332, 'HT', 'HTI', 'Sovereign State'),
('Heard Island and McDonald Islands', 0, 334, 'HM', 'HMD', 'Special Entity'),
('Holy See', 0, 336, 'VA', 'VAT', 'Sovereign State'),
('Honduras', 0, 340, 'HN', 'HND', 'Sovereign State'),
('Hong Kong', 0, 344, 'HK', 'HKG', 'Autonomous Region'),
('Hungary', 0, 348, 'HU', 'HUN', 'Sovereign State'),
('Iceland', 0, 352, 'IS', 'ISL', 'Sovereign State'),
('India', 0, 356, 'IN', 'IND', 'Sovereign State'),
('Indonesia', 0, 360, 'ID', 'IDN', 'Sovereign State'),
('Iran, Islamic Republic of', 0, 364, 'IR', 'IRN', 'Sovereign State'),
('Iraq', 0, 368, 'IQ', 'IRQ', 'Sovereign State'),
('Ireland', 0, 372, 'IE', 'IRL', 'Sovereign State'),
('Isle of Man', 0, 833, 'IM', 'IMN', 'Dependency'),
('Israel', 0, 376, 'IL', 'ISR', 'Sovereign State'),
('Italy', 0, 380, 'IT', 'ITA', 'Sovereign State'),
('Jamaica', 0, 388, 'JM', 'JAM', 'Sovereign State'),
('Japan', 0, 392, 'JP', 'JPN', 'Sovereign State'),
('Jersey', 0, 832, 'JE', 'JEY', 'Dependency'),
('Jordan', 0, 400, 'JO', 'JOR', 'Sovereign State'),
('Kazakhstan', 0, 398, 'KZ', 'KAZ', 'Sovereign State'),
('Kenya', 0, 404, 'KE', 'KEN', 'Sovereign State'),
('Kiribati', 0, 296, 'KI', 'KIR', 'Sovereign State'),
('Korea, Democratic People''s Republic of', 0, 408, 'KP', 'PRK', 'Sovereign State'),
('Korea, Republic of', 0, 410, 'KR', 'KOR', 'Sovereign State'),
('Kuwait', 0, 414, 'KW', 'KWT', 'Sovereign State'),
('Kyrgyzstan', 0, 417, 'KG', 'KGZ', 'Sovereign State'),
('Lao People''s Democratic Republic', 0, 418, 'LA', 'LAO', 'Sovereign State'),
('Latvia', 0, 428, 'LV', 'LVA', 'Sovereign State'),
('Lebanon', 0, 422, 'LB', 'LBN', 'Sovereign State'),
('Lesotho', 0, 426, 'LS', 'LSO', 'Sovereign State'),
('Liberia', 0, 430, 'LR', 'LBR', 'Sovereign State'),
('Libya', 0, 434, 'LY', 'LBY', 'Sovereign State'),
('Liechtenstein', 0, 438, 'LI', 'LIE', 'Sovereign State'),
('Lithuania', 0, 440, 'LT', 'LTU', 'Sovereign State'),
('Luxembourg', 0, 442, 'LU', 'LUX', 'Sovereign State'),
('Macao', 0, 446, 'MO', 'MAC', 'Autonomous Region'),
('Madagascar', 0, 450, 'MG', 'MDG', 'Sovereign State'),
('Malawi', 0, 454, 'MW', 'MWI', 'Sovereign State'),
('Malaysia', 0, 458, 'MY', 'MYS', 'Sovereign State'),
('Maldives', 0, 462, 'MV', 'MDV', 'Sovereign State'),
('Mali', 0, 466, 'ML', 'MLI', 'Sovereign State'),
('Malta', 0, 470, 'MT', 'MLT', 'Sovereign State'),
('Marshall Islands', 0, 584, 'MH', 'MHL', 'Sovereign State'),
('Martinique', 0, 474, 'MQ', 'MTQ', 'Dependency'),
('Mauritania', 0, 478, 'MR', 'MRT', 'Sovereign State'),
('Mauritius', 0, 480, 'MU', 'MUS', 'Sovereign State'),
('Mayotte', 0, 175, 'YT', 'MYT', 'Dependency'),
('Mexico', 0, 484, 'MX', 'MEX', 'Sovereign State'),
('Micronesia, Federated States of', 0, 583, 'FM', 'FSM', 'Sovereign State'),
('Moldova, Republic of', 0, 498, 'MD', 'MDA', 'Sovereign State'),
('Monaco', 0, 492, 'MC', 'MCO', 'Sovereign State'),
('Mongolia', 0, 496, 'MN', 'MNG', 'Sovereign State'),
('Montenegro', 0, 499, 'ME', 'MNE', 'Sovereign State'),
('Montserrat', 0, 500, 'MS', 'MSR', 'Dependency'),
('Morocco', 0, 504, 'MA', 'MAR', 'Sovereign State'),
('Mozambique', 0, 508, 'MZ', 'MOZ', 'Sovereign State'),
('Myanmar', 0, 104, 'MM', 'MMR', 'Sovereign State'),
('Namibia', 0, 516, 'NA', 'NAM', 'Sovereign State'),
('Nauru', 0, 520, 'NR', 'NRU', 'Sovereign State'),
('Nepal', 0, 524, 'NP', 'NPL', 'Sovereign State'),
('Netherlands, Kingdom of the', 0, 528, 'NL', 'NLD', 'Sovereign State'),
('New Caledonia', 0, 540, 'NC', 'NCL', 'Dependency'),
('New Zealand', 0, 554, 'NZ', 'NZL', 'Sovereign State'),
('Nicaragua', 0, 558, 'NI', 'NIC', 'Sovereign State'),
('Niger', 0, 562, 'NE', 'NER', 'Sovereign State'),
('Nigeria', 0, 566, 'NG', 'NGA', 'Sovereign State'),
('Niue', 0, 570, 'NU', 'NIU', 'Autonomous Region'),
('Norfolk Island', 0, 574, 'NF', 'NFK', 'Dependency'),
('North Macedonia', 0, 807, 'MK', 'MKD', 'Sovereign State'),
('Northern Mariana Islands', 0, 580, 'MP', 'MNP', 'Dependency'),
('Norway', 0, 578, 'NO', 'NOR', 'Sovereign State'),
('Oman', 0, 512, 'OM', 'OMN', 'Sovereign State'),
('Pakistan', 0, 586, 'PK', 'PAK', 'Sovereign State'),
('Palau', 0, 585, 'PW', 'PLW', 'Sovereign State'),
('Palestine, State of', 0, 275, 'PS', 'PSE', 'Sovereign State'),
('Panama', 0, 591, 'PA', 'PAN', 'Sovereign State'),
('Papua New Guinea', 0, 598, 'PG', 'PNG', 'Sovereign State'),
('Paraguay', 0, 600, 'PY', 'PRY', 'Sovereign State'),
('Peru', 0, 604, 'PE', 'PER', 'Sovereign State'),
('Philippines', 0, 608, 'PH', 'PHL', 'Sovereign State'),
('Pitcairn', 0, 612, 'PN', 'PCN', 'Dependency'),
('Poland', 0, 616, 'PL', 'POL', 'Sovereign State'),
('Portugal', 0, 620, 'PT', 'PRT', 'Sovereign State'),
('Puerto Rico', 0, 630, 'PR', 'PRI', 'Dependency'),
('Qatar', 0, 634, 'QA', 'QAT', 'Sovereign State'),
('Réunion', 0, 638, 'RE', 'REU', 'Dependency'),
('Romania', 0, 642, 'RO', 'ROU', 'Sovereign State'),
('Russian Federation', 0, 643, 'RU', 'RUS', 'Sovereign State'),
('Rwanda', 0, 646, 'RW', 'RWA', 'Sovereign State'),
('Saint Barthélemy', 0, 652, 'BL', 'BLM', 'Dependency'),
('Saint Helena, Ascension and Tristan da Cunha', 0, 654, 'SH', 'SHN', 'Dependency'),
('Saint Kitts and Nevis', 0, 659, 'KN', 'KNA', 'Sovereign State'),
('Saint Lucia', 0, 662, 'LC', 'LCA', 'Sovereign State'),
('Saint Martin (French part)', 0, 663, 'MF', 'MAF', 'Dependency'),
('Saint Pierre and Miquelon', 0, 666, 'PM', 'SPM', 'Dependency'),
('Saint Vincent and the Grenadines', 0, 670, 'VC', 'VCT', 'Sovereign State'),
('Samoa', 0, 882, 'WS', 'WSM', 'Sovereign State'),
('San Marino', 0, 674, 'SM', 'SMR', 'Sovereign State'),
('Sao Tome and Principe', 0, 678, 'ST', 'STP', 'Sovereign State'),
('Saudi Arabia', 0, 682, 'SA', 'SAU', 'Sovereign State'),
('Senegal', 0, 686, 'SN', 'SEN', 'Sovereign State'),
('Serbia', 0, 688, 'RS', 'SRB', 'Sovereign State'),
('Seychelles', 0, 690, 'SC', 'SYC', 'Sovereign State'),
('Sierra Leone', 0, 694, 'SL', 'SLE', 'Sovereign State'),
('Singapore', 0, 702, 'SG', 'SGP', 'Sovereign State'),
('Sint Maarten (Dutch part)', 0, 534, 'SX', 'SXM', 'Dependency'),
('Slovakia', 0, 703, 'SK', 'SVK', 'Sovereign State'),
('Slovenia', 0, 705, 'SI', 'SVN', 'Sovereign State'),
('Solomon Islands', 0, 90, 'SB', 'SLB', 'Sovereign State'),
('Somalia', 0, 706, 'SO', 'SOM', 'Sovereign State'),
('South Africa', 0, 710, 'ZA', 'ZAF', 'Sovereign State'),
('South Georgia and the South Sandwich Islands', 0, 239, 'GS', 'GGS', 'Special Entity'),
('South Sudan', 0, 728, 'SS', 'SSD', 'Sovereign State'),
('Spain', 0, 724, 'ES', 'ESP', 'Sovereign State'),
('Sri Lanka', 0, 144, 'LK', 'LKA', 'Sovereign State'),
('Sudan', 0, 729, 'SD', 'SDN', 'Sovereign State'),
('Suriname', 0, 740, 'SR', 'SUR', 'Sovereign State'),
('Svalbard and Jan Mayen', 0, 744, 'SJ', 'SJM', 'Special Entity'),
('Sweden', 0, 752, 'SE', 'SWE', 'Sovereign State'),
('Switzerland', 0, 756, 'CH', 'CHE', 'Sovereign State'),
('Syrian Arab Republic', 0, 760, 'SY', 'SYR', 'Sovereign State'),
('Taiwan, Province of China', 0, 158, 'TW', 'TWN', 'Autonomous Region'),
('Tajikistan', 0, 762, 'TJ', 'TJK', 'Sovereign State'),
('Tanzania, United Republic of', 0, 834, 'TZ', 'TZA', 'Sovereign State'),
('Thailand', 0, 764, 'TH', 'THA', 'Sovereign State'),
('Timor-Leste', 0, 626, 'TL', 'TLS', 'Sovereign State'),
('Togo', 0, 768, 'TG', 'TGO', 'Sovereign State'),
('Tokelau', 0, 772, 'TK', 'TKL', 'Dependency'),
('Tonga', 0, 776, 'TO', 'TON', 'Sovereign State'),
('Trinidad and Tobago', 0, 780, 'TT', 'TTO', 'Sovereign State'),
('Tunisia', 0, 788, 'TN', 'TUN', 'Sovereign State'),
('Türkiye', 0, 792, 'TR', 'TUR', 'Sovereign State'),
('Turkmenistan', 0, 795, 'TM', 'TKM', 'Sovereign State'),
('Turks and Caicos Islands', 0, 796, 'TC', 'TCA', 'Dependency'),
('Tuvalu', 0, 798, 'TV', 'TUV', 'Sovereign State'),
('Uganda', 0, 800, 'UG', 'UGA', 'Sovereign State'),
('Ukraine', 0, 804, 'UA', 'UKR', 'Sovereign State'),
('United Arab Emirates', 0, 784, 'AE', 'ARE', 'Sovereign State'),
('United Kingdom of Great Britain and Northern Ireland', 0, 826, 'GB', 'GBR', 'Sovereign State'),
('United States Minor Outlying Islands', 0, 581, 'UM', 'UMI', 'Special Entity'),
('United States of America', 0, 840, 'US', 'USA', 'Sovereign State'),
('Uruguay', 0, 858, 'UY', 'URY', 'Sovereign State'),
('Uzbekistan', 0, 860, 'UZ', 'UZB', 'Sovereign State'),
('Vanuatu', 0, 548, 'VU', 'VUT', 'Sovereign State'),
('Venezuela, Bolivarian Republic of', 0, 862, 'VE', 'VEN', 'Sovereign State'),
('Viet Nam', 0, 704, 'VN', 'VNM', 'Sovereign State'),
('Virgin Islands (British)', 0, 92, 'VG', 'VGB', 'Dependency'),
('Virgin Islands (U.S.)', 0, 850, 'VI', 'VIR', 'Dependency'),
('Wallis and Futuna', 0, 876, 'WF', 'WLF', 'Dependency'),
('Western Sahara', 0, 732, 'EH', 'ESH', 'Special Entity'),
('Yemen', 0, 887, 'YE', 'YEM', 'Sovereign State'),
('Zambia', 0, 894, 'ZM', 'ZMB', 'Sovereign State'),
('Zimbabwe', 0, 716, 'ZW', 'ZWE', 'Sovereign State');